version: '2'
services:
  app:
    build: .
    volumes:
      - .:/home/docker/udemy_elixir
    command: bash -c "cd discuss && mix local.hex --force && mix deps.get && mix phoenix.server"
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
   image: postgres:9.6.1
   environment:
     POSTGRES_USER: discuss
     POSTGRES_PASSWORD: discuss
     POSTGRES_DB: discuss_dev
   volumes:
     - ./dockerdata/postgresql:/var/lib/postgresql
  pgadmin:
    image: fenglc/pgadmin4:1.1
    ports:
      - "5050:5050"
    depends_on:
      - postgres
